server:
  tomcat:
    uri-encoding: UTF-8
    threads:
      max: 200
      min-spare: 30
    connection-timeout: 5000ms
  port: 8080
  servlet:
    context-path: /emos-wx-api


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/emos?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver



mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.lx.emos.wx.db.pojo
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

  redis:
    database: 0
    host: localhost
    port: 6379
    password: abc123456
    jedis:
      pool:
        max-active: 1000
        max-wait: -1ms
        max-idle: 16
        min-idle: 8

logging:
  level:
    root: info
    com.lx.emos.wx.db.dao : warn
  pattern:
    console: "%d{HH:mm:ss}  %-5level  %msg%n"



emos:
  jwt:
    secret: 123456
    expire: 5
    cache-expire: 10

wx:
  app-id: wx0af238e0dbd5b343
  app-secret: 7cedfc91816a9900cfe6199c956b7c94
